export const Areas: string[] = [
  'zh.k. Razsadnika',
  'lyulin 1',
  'Gotse Delchev',
  'kv. Reduta',
  'zh.k. Zona B-18',
  'zh.k. Druzhba 1',
  'v.z.Malinova Dolina',
  'v.z.Malinova Dolina - Gerena',
  'Bunkera v.z.',
  'mladost 1',
  'krasno selo',
  's.Gara Yana',
  'Obelya 2',
  'fondovi zhilishta',
  'Gardova glava',
  'Ivan Vazov',
  'kv. Geo Milev',
  'borovo',
  'belite brezi',
  'hladilnika',
  'Simeonovo',
  'Dianabad',
  'do Meditsinska akademiya',
  'Yavorov',
  'kv. Chelopechene',
  'sveta troitsa',
  'Krasna polyana 3',
  'kv. Vrazhdebna',
  'nadezhda 2',
  'Nadezhda 3',
  'zh.k. Hipodruma',
  'Oborishte',
  'Druzhba 2',
  'kv. Vitosha',
  'zh.k. Lyulin 8',
  'Strelbishte',
  'lyulin 3',
  'zh.k. Nadezhda 1',
  'suha reka',
  'Poduyane',
  'Krastova vada',
  'dobroslavtsi',
  'Mladost 2',
  'Boyana',
  'Tsentar',
  'zh.k. Mladost 3',
  'zh.k. Lyulin 6',
  'zaharna fabrika',
  'Mladost 4',
  'zh.k. Lyulin 5',
  'kv. Dragalevtsi',
  'zh.k. Zona B-19',
  'kv. Darvenitsa',
  'Pavlovo',
  'krasna polyana',
  'Iztok',
  'Musagenitsa',
  'zh.k. Studentski grad',
  'zh.k. Lyulin 9',
  'Malashevtsi',
  'kv. Ovcha kupel',
  's.Pancharevo',
  'Zona B-5',
  'gorna banya',
  'Vrabnitsa 2',
  'ilinden',
  'karpuzitsa',
  'bankya',
  'knyazhevo',
  'Lyulin 2',
  'tolstoy',
  'zh.k. Levski-G',
  'Busmantsi',
  'v.z.Bunkera',
  'kv. Suhodol',
  'gr.Bankya',
  'bistritsa',
  'krivina',
  'Serdika',
  'triagalnika',
  'kv. Kremikovtsi',
  'moderno predgradie',
  'kv. Izgrev',
  'Doktorski pametnik',
  'voynegovtsi',
  'Aerogara',
  'zh.k. Banishora',
  'Obelya 1',
  'zh.k. Svoboda',
  'zh.k. Slatina',
  'kv. Levski',
  'lyulin 7',
  'vranya',
  'zh.k. Nadezhda 4',
  'v.z. Belovodski pat',
  'Poligona',
  'Botunets',
  'zh.k. Lyulin 4',
  'Republika',
  'Filipovtsi',
  'kv. Gorublyane',
  'zona b5',
  'NPZ Iskar',
  'kv. Gevgeliyski',
  'zh.k. Bakston',
  'zh.k. Suhata reka',
  'Voenna rampa',
  'kv. Benkovski',
  's.Bistritsa',
  'kv. Orlandovtsi',
  'v.z. Kiliite',
  'vladaya',
  'kv. Fakulteta',
  '7-mi 11-ti kilometar',
  'kv. Iliyantsi',
  'zh.k. Vrabnitsa 1',
  'kokalyane',
  'gorni bogrov',
  'klisura',
  'chepintsi',
  'mramor',
  'v.z.Amerikanski kolezh',
  'tsentralna gara',
  'trebich',
  'pirogov',
  'botevgradsko shose',
  'pasarel',
  'lozen',
  'kv. Seslavtsi',
  'mirovyane',
  'marchaevo',
  'gara iskar',
  'slaviya',
  'motopista',
  'okolovrasten pat',
  'novi iskar',
  'hadzhi dimitar',
  'katina',
  'Letishte Sofiya',
  'kubratovo',
  'v.z.Kiliite',
  'Kumaritsa',
  'zhelyava',
  'dolni bogrov',
  'poduene',
  'zhiten',
  'podgumer',
  'voluyak',
  'kriva reka',
  'hristo botev',
  'm-t Detski grad',
  'negovan',
  'chelopechene',
  'german',
  'lozenets',
  'zheleznitsa',
  'nadezhda 5',
  'obelya',
  'ivanyane',
  'dolni pasarel',
  'plana',
  'svetovrachene',
  'tsarigradsko shose',
  'balsha',
  'malo buchino',
  'yana',
  'Meditsinska akademiya',
  'abdovitsa',
  'pancharevo',
  'Lagera',
  'dimitar milenkov',
  'zh.gr.Yuzhen park',
  'bul. Balgariya',
  'Gnilyane',
  'zona b18',
  'kv. Manastirski livadi',
  'v.z.Mogilata',
  'v.z.Simeonovo - Dragalevtsi',
  'v.z.Milkova koria',
  'm-t Orehite',
  'v.z.Dragalevtsi lifta',
  'v.z.Kinocentar',
  'Malinova dolina',
  'Gradina',
  'v.z.Gabaro - Azmata',
  'm-t Kinocentar',
  'NPZ Iztok',
  'v.z.Boyana',
  'v.z.Kinocentar 3 chast',
  'Mladost 1A',
  'Rezidencia Boyana',
  'm-t Mala koria',
  'Zoopark',
  'zh.gr.Zoopark',
  'PZ Hladilnika',
  'v.z.Gorna bania',
  'SPZ Slatina',
  'Ovcha kupel 2',
  'NPZ Sredets',
  'm-t Podlozishte',
  'Krasna polyana 2',
  'Zona B-5-3',
  'NPZ hadzhi dimitar',
  'Levski V',
  'm-t Bateriata',
  'm-t Ialadzha',
  'Lyulin 10',
  'Lyulin - centar',
  'SPZ Moderno predgradie',
  'PZ Iliyantsi',
  'kv. Zapaden park'
];
